using ChunithmClientLibrary;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace ChunithmClientLibraryUnitTest
{
    [TestClass]
    [TestCategory(TestUtility.Category.Utility)]
    public class OverPowerTest
    {
        private void Check(double expectedOverPower, double baseRating, int score, ComboStatus comboStatus)
        {
            var overPower = Utility.GetOverPower(baseRating, score, comboStatus);
            Assert.AreEqual(expectedOverPower, overPower);
        }

        private void Check_ボーダー(double expectedOverPower, double baseRating, Rank rank, ComboStatus comboStatus)
        {
            Check(expectedOverPower, baseRating, Utility.GetBorderScore(rank), comboStatus);
        }

        private void Check_中間値(double expectedOverPower, double baseRating, Rank rank1, Rank rank2, ComboStatus comboStatus)
        {
            Check(expectedOverPower, baseRating, (Utility.GetBorderScore(rank1) + Utility.GetBorderScore(rank2)) / 2, comboStatus);
        }

        private void Check_ボーダー境界(double expectedOverPower, double baseRating, Rank rank, ComboStatus comboStatus)
        {
            Check(expectedOverPower, baseRating, Utility.GetBorderScore(rank) - 1, comboStatus);
        }

        private void Check_中間値境界(double expectedOverPower, double baseRating, Rank rank1, Rank rank2, ComboStatus comboStatus)
        {
            Check(expectedOverPower, baseRating, (Utility.GetBorderScore(rank1) + Utility.GetBorderScore(rank2)) / 2 - 1, comboStatus);
        }

        private void Check_範囲外(double expectedOverPower, double baseRating, int score, ComboStatus comboStatus)
        {
            Check(expectedOverPower, baseRating, score, comboStatus);
        }

        [TestMethod]
        public void GetOverPowerTest_ボーダー()
        {
            Check_ボーダー(0, 3, Rank.AA, ComboStatus.None);
            Check_ボーダー(0, 3, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー(0, 3, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー(15.0, 3, Rank.S, ComboStatus.None);
            Check_ボーダー(15.5, 3, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー(16.0, 3, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー(20.0, 3, Rank.SS, ComboStatus.None);
            Check_ボーダー(20.5, 3, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー(21.0, 3, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー(22.5, 3, Rank.SSA, ComboStatus.None);
            Check_ボーダー(23.0, 3, Rank.SSA, ComboStatus.FullCombo);
            Check_ボーダー(23.5, 3, Rank.SSA, ComboStatus.AllJustice);
            Check_ボーダー(25.0, 3, Rank.SSS, ComboStatus.None);
            Check_ボーダー(25.5, 3, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー(26.0, 3, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー(30.0, 3, Rank.Max, ComboStatus.None);
            Check_ボーダー(30.0, 3, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー(30.0, 3, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー(0, 5, Rank.A, ComboStatus.None);
            Check_ボーダー(0, 5, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー(0, 5, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー(10.0, 5, Rank.AA, ComboStatus.None);
            Check_ボーダー(10.5, 5, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー(11.0, 5, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー(25.0, 5, Rank.S, ComboStatus.None);
            Check_ボーダー(25.5, 5, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー(26.0, 5, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー(30.0, 5, Rank.SS, ComboStatus.None);
            Check_ボーダー(30.5, 5, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー(31.0, 5, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー(32.5, 5, Rank.SSA, ComboStatus.None);
            Check_ボーダー(33.0, 5, Rank.SSA, ComboStatus.FullCombo);
            Check_ボーダー(33.5, 5, Rank.SSA, ComboStatus.AllJustice);
            Check_ボーダー(35.0, 5, Rank.SSS, ComboStatus.None);
            Check_ボーダー(35.5, 5, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー(36.0, 5, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー(40.0, 5, Rank.Max, ComboStatus.None);
            Check_ボーダー(40.0, 5, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー(40.0, 5, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー(0, 13, Rank.C, ComboStatus.None);
            Check_ボーダー(0, 13, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー(0, 13, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー(20.0, 13, Rank.BBB, ComboStatus.None);
            Check_ボーダー(20.5, 13, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー(21.0, 13, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー(40.0, 13, Rank.A, ComboStatus.None);
            Check_ボーダー(40.5, 13, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー(41.0, 13, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー(50.0, 13, Rank.AA, ComboStatus.None);
            Check_ボーダー(50.5, 13, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー(51.0, 13, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー(65.0, 13, Rank.S, ComboStatus.None);
            Check_ボーダー(65.5, 13, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー(66.0, 13, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー(70.0, 13, Rank.SS, ComboStatus.None);
            Check_ボーダー(70.5, 13, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー(71.0, 13, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー(75.0, 13, Rank.SSS, ComboStatus.None);
            Check_ボーダー(75.5, 13, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー(76.0, 13, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー(80.0, 13, Rank.Max, ComboStatus.None);
            Check_ボーダー(80.0, 13, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー(80.0, 13, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー(0, 13.1, Rank.C, ComboStatus.None);
            Check_ボーダー(0, 13.1, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー(0, 13.1, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー(20.25, 13.1, Rank.BBB, ComboStatus.None);
            Check_ボーダー(20.75, 13.1, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー(21.25, 13.1, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー(40.50, 13.1, Rank.A, ComboStatus.None);
            Check_ボーダー(41.00, 13.1, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー(41.50, 13.1, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー(50.50, 13.1, Rank.AA, ComboStatus.None);
            Check_ボーダー(51.00, 13.1, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー(51.50, 13.1, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー(65.50, 13.1, Rank.S, ComboStatus.None);
            Check_ボーダー(66.00, 13.1, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー(66.50, 13.1, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー(70.50, 13.1, Rank.SS, ComboStatus.None);
            Check_ボーダー(71.00, 13.1, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー(71.50, 13.1, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー(75.50, 13.1, Rank.SSS, ComboStatus.None);
            Check_ボーダー(76.00, 13.1, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー(76.50, 13.1, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー(80.50, 13.1, Rank.Max, ComboStatus.None);
            Check_ボーダー(80.50, 13.1, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー(80.50, 13.1, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー(0, 13.2, Rank.C, ComboStatus.None);
            Check_ボーダー(0, 13.2, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー(0, 13.2, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー(20.50, 13.2, Rank.BBB, ComboStatus.None);
            Check_ボーダー(21.00, 13.2, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー(21.50, 13.2, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー(41.00, 13.2, Rank.A, ComboStatus.None);
            Check_ボーダー(41.50, 13.2, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー(42.00, 13.2, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー(51.00, 13.2, Rank.AA, ComboStatus.None);
            Check_ボーダー(51.50, 13.2, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー(52.00, 13.2, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー(66.00, 13.2, Rank.S, ComboStatus.None);
            Check_ボーダー(66.50, 13.2, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー(67.00, 13.2, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー(71.00, 13.2, Rank.SS, ComboStatus.None);
            Check_ボーダー(71.50, 13.2, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー(72.00, 13.2, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー(76.00, 13.2, Rank.SSS, ComboStatus.None);
            Check_ボーダー(76.50, 13.2, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー(77.00, 13.2, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー(81.00, 13.2, Rank.Max, ComboStatus.None);
            Check_ボーダー(81.00, 13.2, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー(81.00, 13.2, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー(0, 13.3, Rank.C, ComboStatus.None);
            Check_ボーダー(0, 13.3, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー(0, 13.3, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー(20.75, 13.3, Rank.BBB, ComboStatus.None);
            Check_ボーダー(21.25, 13.3, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー(21.75, 13.3, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー(41.50, 13.3, Rank.A, ComboStatus.None);
            Check_ボーダー(42.00, 13.3, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー(42.50, 13.3, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー(51.50, 13.3, Rank.AA, ComboStatus.None);
            Check_ボーダー(52.00, 13.3, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー(52.50, 13.3, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー(66.50, 13.3, Rank.S, ComboStatus.None);
            Check_ボーダー(67.00, 13.3, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー(67.50, 13.3, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー(71.50, 13.3, Rank.SS, ComboStatus.None);
            Check_ボーダー(72.00, 13.3, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー(72.50, 13.3, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー(76.50, 13.3, Rank.SSS, ComboStatus.None);
            Check_ボーダー(77.00, 13.3, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー(77.50, 13.3, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー(81.50, 13.3, Rank.Max, ComboStatus.None);
            Check_ボーダー(81.50, 13.3, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー(81.50, 13.3, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー(0, 13.4, Rank.C, ComboStatus.None);
            Check_ボーダー(0, 13.4, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー(0, 13.4, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー(21.00, 13.4, Rank.BBB, ComboStatus.None);
            Check_ボーダー(21.50, 13.4, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー(22.00, 13.4, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー(42.00, 13.4, Rank.A, ComboStatus.None);
            Check_ボーダー(42.50, 13.4, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー(43.00, 13.4, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー(52.00, 13.4, Rank.AA, ComboStatus.None);
            Check_ボーダー(52.50, 13.4, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー(53.00, 13.4, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー(67.00, 13.4, Rank.S, ComboStatus.None);
            Check_ボーダー(67.50, 13.4, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー(68.00, 13.4, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー(72.00, 13.4, Rank.SS, ComboStatus.None);
            Check_ボーダー(72.50, 13.4, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー(73.00, 13.4, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー(77.00, 13.4, Rank.SSS, ComboStatus.None);
            Check_ボーダー(77.50, 13.4, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー(78.00, 13.4, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー(82.00, 13.4, Rank.Max, ComboStatus.None);
            Check_ボーダー(82.00, 13.4, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー(82.00, 13.4, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー(0, 13.5, Rank.C, ComboStatus.None);
            Check_ボーダー(0, 13.5, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー(0, 13.5, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー(21.25, 13.5, Rank.BBB, ComboStatus.None);
            Check_ボーダー(21.75, 13.5, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー(22.25, 13.5, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー(42.50, 13.5, Rank.A, ComboStatus.None);
            Check_ボーダー(43.00, 13.5, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー(43.50, 13.5, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー(52.50, 13.5, Rank.AA, ComboStatus.None);
            Check_ボーダー(53.00, 13.5, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー(53.50, 13.5, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー(67.50, 13.5, Rank.S, ComboStatus.None);
            Check_ボーダー(68.00, 13.5, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー(68.50, 13.5, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー(72.50, 13.5, Rank.SS, ComboStatus.None);
            Check_ボーダー(73.00, 13.5, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー(73.50, 13.5, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー(77.50, 13.5, Rank.SSS, ComboStatus.None);
            Check_ボーダー(78.00, 13.5, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー(78.50, 13.5, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー(82.50, 13.5, Rank.Max, ComboStatus.None);
            Check_ボーダー(82.50, 13.5, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー(82.50, 13.5, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー(0, 13.6, Rank.C, ComboStatus.None);
            Check_ボーダー(0, 13.6, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー(0, 13.6, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー(21.50, 13.6, Rank.BBB, ComboStatus.None);
            Check_ボーダー(22.00, 13.6, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー(22.50, 13.6, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー(43.00, 13.6, Rank.A, ComboStatus.None);
            Check_ボーダー(43.50, 13.6, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー(44.00, 13.6, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー(53.00, 13.6, Rank.AA, ComboStatus.None);
            Check_ボーダー(53.50, 13.6, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー(54.00, 13.6, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー(68.00, 13.6, Rank.S, ComboStatus.None);
            Check_ボーダー(68.50, 13.6, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー(69.00, 13.6, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー(73.00, 13.6, Rank.SS, ComboStatus.None);
            Check_ボーダー(73.50, 13.6, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー(74.00, 13.6, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー(78.00, 13.6, Rank.SSS, ComboStatus.None);
            Check_ボーダー(78.50, 13.6, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー(79.00, 13.6, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー(83.00, 13.6, Rank.Max, ComboStatus.None);
            Check_ボーダー(83.00, 13.6, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー(83.00, 13.6, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー(0, 13.7, Rank.C, ComboStatus.None);
            Check_ボーダー(0, 13.7, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー(0, 13.7, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー(21.75, 13.7, Rank.BBB, ComboStatus.None);
            Check_ボーダー(22.25, 13.7, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー(22.75, 13.7, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー(43.50, 13.7, Rank.A, ComboStatus.None);
            Check_ボーダー(44.00, 13.7, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー(44.50, 13.7, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー(53.50, 13.7, Rank.AA, ComboStatus.None);
            Check_ボーダー(54.00, 13.7, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー(54.50, 13.7, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー(68.50, 13.7, Rank.S, ComboStatus.None);
            Check_ボーダー(69.00, 13.7, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー(69.50, 13.7, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー(73.50, 13.7, Rank.SS, ComboStatus.None);
            Check_ボーダー(74.00, 13.7, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー(74.50, 13.7, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー(78.50, 13.7, Rank.SSS, ComboStatus.None);
            Check_ボーダー(79.00, 13.7, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー(79.50, 13.7, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー(83.50, 13.7, Rank.Max, ComboStatus.None);
            Check_ボーダー(83.50, 13.7, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー(83.50, 13.7, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー(0, 13.8, Rank.C, ComboStatus.None);
            Check_ボーダー(0, 13.8, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー(0, 13.8, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー(22.00, 13.8, Rank.BBB, ComboStatus.None);
            Check_ボーダー(22.50, 13.8, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー(23.00, 13.8, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー(44.00, 13.8, Rank.A, ComboStatus.None);
            Check_ボーダー(44.50, 13.8, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー(45.00, 13.8, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー(54.00, 13.8, Rank.AA, ComboStatus.None);
            Check_ボーダー(54.50, 13.8, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー(55.00, 13.8, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー(69.00, 13.8, Rank.S, ComboStatus.None);
            Check_ボーダー(69.50, 13.8, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー(70.00, 13.8, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー(74.00, 13.8, Rank.SS, ComboStatus.None);
            Check_ボーダー(74.50, 13.8, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー(75.00, 13.8, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー(79.00, 13.8, Rank.SSS, ComboStatus.None);
            Check_ボーダー(79.50, 13.8, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー(80.00, 13.8, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー(84.00, 13.8, Rank.Max, ComboStatus.None);
            Check_ボーダー(84.00, 13.8, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー(84.00, 13.8, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー(0, 13.9, Rank.C, ComboStatus.None);
            Check_ボーダー(0, 13.9, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー(0, 13.9, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー(22.25, 13.9, Rank.BBB, ComboStatus.None);
            Check_ボーダー(22.75, 13.9, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー(23.25, 13.9, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー(44.50, 13.9, Rank.A, ComboStatus.None);
            Check_ボーダー(45.00, 13.9, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー(45.50, 13.9, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー(54.50, 13.9, Rank.AA, ComboStatus.None);
            Check_ボーダー(55.00, 13.9, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー(55.50, 13.9, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー(69.50, 13.9, Rank.S, ComboStatus.None);
            Check_ボーダー(70.00, 13.9, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー(70.50, 13.9, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー(74.50, 13.9, Rank.SS, ComboStatus.None);
            Check_ボーダー(75.00, 13.9, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー(75.50, 13.9, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー(79.50, 13.9, Rank.SSS, ComboStatus.None);
            Check_ボーダー(80.00, 13.9, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー(80.50, 13.9, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー(84.50, 13.9, Rank.Max, ComboStatus.None);
            Check_ボーダー(84.50, 13.9, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー(84.50, 13.9, Rank.Max, ComboStatus.AllJustice);
        }

        [TestMethod]
        public void GetOverPowerTest_中間()
        {
            Check_中間値(0, 3, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値(0, 3, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値(0, 3, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値(7.50, 3, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値(8.00, 3, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値(8.50, 3, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値(17.50, 3, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値(18.00, 3, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値(18.50, 3, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値(21.25, 3, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値(21.75, 3, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値(22.25, 3, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値(23.75, 3, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値(24.25, 3, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値(24.75, 3, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値(26.875, 3, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値(27.375, 3, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値(27.875, 3, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値(0, 5, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値(0, 5, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値(0, 5, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値(5.00, 5, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値(5.50, 5, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値(6.00, 5, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値(17.50, 5, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値(18.00, 5, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値(18.50, 5, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値(27.50, 5, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値(28.00, 5, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値(28.50, 5, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値(31.25, 5, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値(31.75, 5, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値(32.25, 5, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値(33.75, 5, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値(34.25, 5, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値(34.75, 5, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値(36.875, 5, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値(37.375, 5, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値(37.875, 5, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値(0, 6, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値(0, 6, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値(0, 6, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値(1.25, 6, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値(1.75, 6, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値(2.25, 6, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値(3.75, 6, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値(4.25, 6, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値(4.75, 6, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値(10.00, 6, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値(10.50, 6, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値(11.00, 6, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値(22.50, 6, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値(23.00, 6, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値(23.50, 6, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値(32.50, 6, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値(33.00, 6, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値(33.50, 6, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値(36.25, 6, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値(36.75, 6, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値(37.25, 6, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値(38.75, 6, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値(39.25, 6, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値(39.75, 6, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値(41.875, 6, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値(42.375, 6, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値(42.875, 6, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値(0, 13.0, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値(0, 13.0, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値(0, 13.0, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値(10.0, 13.0, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値(10.5, 13.0, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値(11.0, 13.0, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値(30.0, 13.0, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値(30.5, 13.0, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値(31.0, 13.0, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値(45.0, 13.0, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値(45.5, 13.0, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値(46.0, 13.0, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値(57.5, 13.0, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値(58.0, 13.0, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値(58.5, 13.0, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値(67.5, 13.0, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値(68.0, 13.0, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値(68.5, 13.0, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値(71.25, 13.0, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値(71.75, 13.0, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値(72.25, 13.0, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値(73.75, 13.0, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値(74.25, 13.0, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値(74.75, 13.0, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値(76.875, 13.0, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値(77.375, 13.0, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値(77.875, 13.0, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値(0, 13.1, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値(0, 13.1, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値(0, 13.1, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値(10.12, 13.1, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値(10.62, 13.1, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値(11.12, 13.1, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値(30.37, 13.1, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値(30.87, 13.1, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値(31.37, 13.1, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値(45.5, 13.1, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値(46.0, 13.1, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値(46.5, 13.1, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値(58.0, 13.1, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値(58.5, 13.1, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値(59.0, 13.1, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値(68.0, 13.1, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値(68.5, 13.1, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値(69.0, 13.1, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値(71.75, 13.1, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値(72.25, 13.1, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値(72.75, 13.1, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値(74.25, 13.1, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値(74.75, 13.1, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値(75.25, 13.1, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値(77.375, 13.1, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値(77.875, 13.1, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値(78.375, 13.1, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値(0, 13.2, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値(0, 13.2, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値(0, 13.2, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値(10.25, 13.2, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値(10.75, 13.2, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値(11.25, 13.2, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値(30.75, 13.2, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値(31.25, 13.2, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値(31.75, 13.2, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値(46.0, 13.2, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値(46.5, 13.2, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値(47.0, 13.2, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値(58.5, 13.2, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値(59.0, 13.2, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値(59.5, 13.2, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値(68.5, 13.2, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値(69.0, 13.2, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値(69.5, 13.2, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値(72.25, 13.2, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値(72.75, 13.2, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値(73.25, 13.2, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値(74.75, 13.2, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値(75.25, 13.2, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値(75.75, 13.2, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値(77.875, 13.2, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値(78.375, 13.2, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値(78.875, 13.2, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値(0, 13.3, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値(0, 13.3, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値(0, 13.3, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値(10.37, 13.3, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値(10.87, 13.3, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値(11.37, 13.3, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値(31.12, 13.3, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値(31.62, 13.3, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値(32.12, 13.3, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値(46.5, 13.3, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値(47.0, 13.3, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値(47.5, 13.3, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値(59.0, 13.3, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値(59.5, 13.3, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値(60.0, 13.3, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値(69.0, 13.3, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値(69.5, 13.3, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値(70.0, 13.3, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値(72.75, 13.3, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値(73.25, 13.3, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値(73.75, 13.3, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値(75.25, 13.3, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値(75.75, 13.3, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値(76.25, 13.3, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値(78.375, 13.3, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値(78.875, 13.3, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値(79.375, 13.3, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値(0, 13.4, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値(0, 13.4, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値(0, 13.4, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値(10.5, 13.4, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値(11.0, 13.4, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値(11.5, 13.4, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値(31.5, 13.4, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値(32.0, 13.4, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値(32.5, 13.4, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値(47.0, 13.4, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値(47.5, 13.4, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値(48.0, 13.4, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値(59.5, 13.4, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値(60.0, 13.4, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値(60.5, 13.4, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値(69.5, 13.4, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値(70.0, 13.4, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値(70.5, 13.4, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値(73.25, 13.4, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値(73.75, 13.4, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値(74.25, 13.4, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値(75.75, 13.4, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値(76.25, 13.4, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値(76.75, 13.4, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値(78.875, 13.4, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値(79.375, 13.4, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値(79.875, 13.4, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値(0, 13.5, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値(0, 13.5, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値(0, 13.5, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値(10.62, 13.5, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値(11.12, 13.5, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値(11.62, 13.5, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値(31.87, 13.5, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値(32.37, 13.5, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値(32.87, 13.5, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値(47.5, 13.5, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値(48.0, 13.5, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値(48.5, 13.5, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値(60.0, 13.5, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値(60.5, 13.5, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値(61.0, 13.5, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値(70.0, 13.5, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値(70.5, 13.5, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値(71.0, 13.5, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値(73.75, 13.5, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値(74.25, 13.5, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値(74.75, 13.5, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値(76.25, 13.5, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値(76.75, 13.5, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値(77.25, 13.5, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値(79.375, 13.5, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値(79.875, 13.5, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値(80.375, 13.5, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値(0, 13.6, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値(0, 13.6, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値(0, 13.6, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値(10.75, 13.6, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値(11.25, 13.6, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値(11.75, 13.6, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値(32.25, 13.6, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値(32.75, 13.6, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値(33.25, 13.6, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値(48.0, 13.6, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値(48.5, 13.6, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値(49.0, 13.6, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値(60.5, 13.6, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値(61.0, 13.6, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値(61.5, 13.6, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値(70.5, 13.6, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値(71.0, 13.6, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値(71.5, 13.6, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値(74.25, 13.6, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値(74.75, 13.6, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値(75.25, 13.6, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値(76.75, 13.6, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値(77.25, 13.6, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値(77.75, 13.6, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値(79.875, 13.6, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値(80.375, 13.6, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値(80.875, 13.6, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値(0, 13.7, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値(0, 13.7, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値(0, 13.7, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値(10.87, 13.7, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値(11.37, 13.7, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値(11.87, 13.7, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値(32.62, 13.7, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値(33.12, 13.7, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値(33.62, 13.7, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値(48.5, 13.7, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値(49.0, 13.7, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値(49.5, 13.7, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値(61.0, 13.7, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値(61.5, 13.7, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値(62.0, 13.7, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値(71.0, 13.7, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値(71.5, 13.7, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値(72.0, 13.7, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値(74.75, 13.7, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値(75.25, 13.7, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値(75.75, 13.7, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値(77.25, 13.7, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値(77.75, 13.7, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値(78.25, 13.7, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値(80.375, 13.7, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値(80.875, 13.7, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値(81.375, 13.7, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値(0, 13.8, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値(0, 13.8, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値(0, 13.8, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値(11.0, 13.8, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値(11.5, 13.8, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値(12.0, 13.8, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値(33.0, 13.8, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値(33.5, 13.8, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値(34.0, 13.8, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値(49.0, 13.8, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値(49.5, 13.8, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値(50.0, 13.8, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値(61.5, 13.8, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値(62.0, 13.8, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値(62.5, 13.8, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値(71.5, 13.8, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値(72.0, 13.8, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値(72.5, 13.8, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値(75.25, 13.8, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値(75.75, 13.8, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値(76.25, 13.8, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値(77.75, 13.8, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値(78.25, 13.8, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値(78.75, 13.8, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値(80.875, 13.8, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値(81.375, 13.8, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値(81.875, 13.8, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値(0, 13.9, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値(0, 13.9, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値(0, 13.9, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値(11.12, 13.9, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値(11.62, 13.9, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値(12.12, 13.9, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値(33.37, 13.9, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値(33.87, 13.9, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値(34.37, 13.9, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値(49.5, 13.9, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値(50.0, 13.9, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値(50.5, 13.9, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値(62.0, 13.9, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値(62.5, 13.9, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値(63.0, 13.9, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値(72.0, 13.9, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値(72.5, 13.9, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値(73.0, 13.9, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値(75.75, 13.9, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値(76.25, 13.9, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値(76.75, 13.9, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値(78.25, 13.9, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値(78.75, 13.9, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値(79.25, 13.9, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値(81.375, 13.9, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値(81.875, 13.9, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値(82.375, 13.9, Rank.SSS, Rank.Max, ComboStatus.AllJustice);
        }

        [TestMethod]
        public void GetOverPowerTest_ボーダー境界()
        {
            Check_ボーダー境界(0, 3, Rank.A, ComboStatus.None);
            Check_ボーダー境界(0, 3, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー境界(0, 3, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー境界(0, 3, Rank.AA, ComboStatus.None);
            Check_ボーダー境界(0, 3, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー境界(0, 3, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー境界(14.99, 3, Rank.S, ComboStatus.None);
            Check_ボーダー境界(15.49, 3, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー境界(15.99, 3, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー境界(19.9998, 3, Rank.SS, ComboStatus.None);
            Check_ボーダー境界(20.4998, 3, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー境界(20.9998, 3, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー境界(22.4995, 3, Rank.SSA, ComboStatus.None);
            Check_ボーダー境界(22.9995, 3, Rank.SSA, ComboStatus.FullCombo);
            Check_ボーダー境界(23.4995, 3, Rank.SSA, ComboStatus.AllJustice);
            Check_ボーダー境界(24.999, 3, Rank.SSS, ComboStatus.None);
            Check_ボーダー境界(25.499, 3, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー境界(25.999, 3, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー境界(28.7485, 3, Rank.Max, ComboStatus.None);
            Check_ボーダー境界(29.2485, 3, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー境界(29.7485, 3, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー境界(0, 5, Rank.BBB, ComboStatus.None);
            Check_ボーダー境界(0, 5, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー境界(0, 5, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー境界(0, 5, Rank.A, ComboStatus.None);
            Check_ボーダー境界(0, 5, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー境界(0, 5, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー境界(9.99, 5, Rank.AA, ComboStatus.None);
            Check_ボーダー境界(10.49, 5, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー境界(10.99, 5, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー境界(24.99, 5, Rank.S, ComboStatus.None);
            Check_ボーダー境界(25.49, 5, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー境界(25.99, 5, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー境界(29.9998, 5, Rank.SS, ComboStatus.None);
            Check_ボーダー境界(30.4998, 5, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー境界(30.9998, 5, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー境界(32.4995, 5, Rank.SSA, ComboStatus.None);
            Check_ボーダー境界(32.9995, 5, Rank.SSA, ComboStatus.FullCombo);
            Check_ボーダー境界(33.4995, 5, Rank.SSA, ComboStatus.AllJustice);
            Check_ボーダー境界(34.999, 5, Rank.SSS, ComboStatus.None);
            Check_ボーダー境界(35.499, 5, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー境界(35.999, 5, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー境界(38.7485, 5, Rank.Max, ComboStatus.None);
            Check_ボーダー境界(39.2485, 5, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー境界(39.7485, 5, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー境界(0, 13.0, Rank.C, ComboStatus.None);
            Check_ボーダー境界(0, 13.0, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー境界(0, 13.0, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー境界(19.99, 13.0, Rank.BBB, ComboStatus.None);
            Check_ボーダー境界(20.49, 13.0, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー境界(20.99, 13.0, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー境界(39.99, 13.0, Rank.A, ComboStatus.None);
            Check_ボーダー境界(40.49, 13.0, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー境界(40.99, 13.0, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー境界(49.99, 13.0, Rank.AA, ComboStatus.None);
            Check_ボーダー境界(50.49, 13.0, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー境界(50.99, 13.0, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー境界(64.99, 13.0, Rank.S, ComboStatus.None);
            Check_ボーダー境界(65.49, 13.0, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー境界(65.99, 13.0, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー境界(69.9998, 13.0, Rank.SS, ComboStatus.None);
            Check_ボーダー境界(70.4998, 13.0, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー境界(70.9998, 13.0, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー境界(72.4995, 13.0, Rank.SSA, ComboStatus.None);
            Check_ボーダー境界(72.9995, 13.0, Rank.SSA, ComboStatus.FullCombo);
            Check_ボーダー境界(73.4995, 13.0, Rank.SSA, ComboStatus.AllJustice);
            Check_ボーダー境界(74.999, 13.0, Rank.SSS, ComboStatus.None);
            Check_ボーダー境界(75.499, 13.0, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー境界(75.999, 13.0, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー境界(78.7485, 13.0, Rank.Max, ComboStatus.None);
            Check_ボーダー境界(79.2485, 13.0, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー境界(79.7485, 13.0, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー境界(0, 13.1, Rank.C, ComboStatus.None);
            Check_ボーダー境界(0, 13.1, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー境界(0, 13.1, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー境界(20.24, 13.1, Rank.BBB, ComboStatus.None);
            Check_ボーダー境界(20.74, 13.1, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー境界(21.24, 13.1, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー境界(40.49, 13.1, Rank.A, ComboStatus.None);
            Check_ボーダー境界(40.99, 13.1, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー境界(41.49, 13.1, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー境界(50.49, 13.1, Rank.AA, ComboStatus.None);
            Check_ボーダー境界(50.99, 13.1, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー境界(51.49, 13.1, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー境界(65.49, 13.1, Rank.S, ComboStatus.None);
            Check_ボーダー境界(65.99, 13.1, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー境界(66.49, 13.1, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー境界(70.4998, 13.1, Rank.SS, ComboStatus.None);
            Check_ボーダー境界(70.9998, 13.1, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー境界(71.4998, 13.1, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー境界(72.9995, 13.1, Rank.SSA, ComboStatus.None);
            Check_ボーダー境界(73.4995, 13.1, Rank.SSA, ComboStatus.FullCombo);
            Check_ボーダー境界(73.9995, 13.1, Rank.SSA, ComboStatus.AllJustice);
            Check_ボーダー境界(75.499, 13.1, Rank.SSS, ComboStatus.None);
            Check_ボーダー境界(75.999, 13.1, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー境界(76.499, 13.1, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー境界(79.2485, 13.1, Rank.Max, ComboStatus.None);
            Check_ボーダー境界(79.7485, 13.1, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー境界(80.2485, 13.1, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー境界(0, 13.2, Rank.C, ComboStatus.None);
            Check_ボーダー境界(0, 13.2, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー境界(0, 13.2, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー境界(20.49, 13.2, Rank.BBB, ComboStatus.None);
            Check_ボーダー境界(20.99, 13.2, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー境界(21.49, 13.2, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー境界(40.99, 13.2, Rank.A, ComboStatus.None);
            Check_ボーダー境界(41.49, 13.2, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー境界(41.99, 13.2, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー境界(50.99, 13.2, Rank.AA, ComboStatus.None);
            Check_ボーダー境界(51.49, 13.2, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー境界(51.99, 13.2, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー境界(65.99, 13.2, Rank.S, ComboStatus.None);
            Check_ボーダー境界(66.49, 13.2, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー境界(66.99, 13.2, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー境界(70.9998, 13.2, Rank.SS, ComboStatus.None);
            Check_ボーダー境界(71.4998, 13.2, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー境界(71.9998, 13.2, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー境界(73.4995, 13.2, Rank.SSA, ComboStatus.None);
            Check_ボーダー境界(73.9995, 13.2, Rank.SSA, ComboStatus.FullCombo);
            Check_ボーダー境界(74.4995, 13.2, Rank.SSA, ComboStatus.AllJustice);
            Check_ボーダー境界(75.999, 13.2, Rank.SSS, ComboStatus.None);
            Check_ボーダー境界(76.499, 13.2, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー境界(76.999, 13.2, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー境界(79.7485, 13.2, Rank.Max, ComboStatus.None);
            Check_ボーダー境界(80.2485, 13.2, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー境界(80.7485, 13.2, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー境界(0, 13.3, Rank.C, ComboStatus.None);
            Check_ボーダー境界(0, 13.3, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー境界(0, 13.3, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー境界(20.74, 13.3, Rank.BBB, ComboStatus.None);
            Check_ボーダー境界(21.24, 13.3, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー境界(21.74, 13.3, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー境界(41.49, 13.3, Rank.A, ComboStatus.None);
            Check_ボーダー境界(41.99, 13.3, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー境界(42.49, 13.3, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー境界(51.49, 13.3, Rank.AA, ComboStatus.None);
            Check_ボーダー境界(51.99, 13.3, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー境界(52.49, 13.3, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー境界(66.49, 13.3, Rank.S, ComboStatus.None);
            Check_ボーダー境界(66.99, 13.3, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー境界(67.49, 13.3, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー境界(71.4998, 13.3, Rank.SS, ComboStatus.None);
            Check_ボーダー境界(71.9998, 13.3, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー境界(72.4998, 13.3, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー境界(73.9995, 13.3, Rank.SSA, ComboStatus.None);
            Check_ボーダー境界(74.4995, 13.3, Rank.SSA, ComboStatus.FullCombo);
            Check_ボーダー境界(74.9995, 13.3, Rank.SSA, ComboStatus.AllJustice);
            Check_ボーダー境界(76.499, 13.3, Rank.SSS, ComboStatus.None);
            Check_ボーダー境界(76.999, 13.3, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー境界(77.499, 13.3, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー境界(80.2485, 13.3, Rank.Max, ComboStatus.None);
            Check_ボーダー境界(80.7485, 13.3, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー境界(81.2485, 13.3, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー境界(0, 13.4, Rank.C, ComboStatus.None);
            Check_ボーダー境界(0, 13.4, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー境界(0, 13.4, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー境界(20.99, 13.4, Rank.BBB, ComboStatus.None);
            Check_ボーダー境界(21.49, 13.4, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー境界(21.99, 13.4, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー境界(41.99, 13.4, Rank.A, ComboStatus.None);
            Check_ボーダー境界(42.49, 13.4, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー境界(42.99, 13.4, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー境界(51.99, 13.4, Rank.AA, ComboStatus.None);
            Check_ボーダー境界(52.49, 13.4, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー境界(52.99, 13.4, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー境界(66.99, 13.4, Rank.S, ComboStatus.None);
            Check_ボーダー境界(67.49, 13.4, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー境界(67.99, 13.4, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー境界(71.9998, 13.4, Rank.SS, ComboStatus.None);
            Check_ボーダー境界(72.4998, 13.4, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー境界(72.9998, 13.4, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー境界(74.4995, 13.4, Rank.SSA, ComboStatus.None);
            Check_ボーダー境界(74.9995, 13.4, Rank.SSA, ComboStatus.FullCombo);
            Check_ボーダー境界(75.4995, 13.4, Rank.SSA, ComboStatus.AllJustice);
            Check_ボーダー境界(76.999, 13.4, Rank.SSS, ComboStatus.None);
            Check_ボーダー境界(77.499, 13.4, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー境界(77.999, 13.4, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー境界(80.7485, 13.4, Rank.Max, ComboStatus.None);
            Check_ボーダー境界(81.2485, 13.4, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー境界(81.7485, 13.4, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー境界(0, 13.5, Rank.C, ComboStatus.None);
            Check_ボーダー境界(0, 13.5, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー境界(0, 13.5, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー境界(21.24, 13.5, Rank.BBB, ComboStatus.None);
            Check_ボーダー境界(21.74, 13.5, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー境界(22.24, 13.5, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー境界(42.49, 13.5, Rank.A, ComboStatus.None);
            Check_ボーダー境界(42.99, 13.5, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー境界(43.49, 13.5, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー境界(52.49, 13.5, Rank.AA, ComboStatus.None);
            Check_ボーダー境界(52.99, 13.5, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー境界(53.49, 13.5, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー境界(67.49, 13.5, Rank.S, ComboStatus.None);
            Check_ボーダー境界(67.99, 13.5, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー境界(68.49, 13.5, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー境界(72.4998, 13.5, Rank.SS, ComboStatus.None);
            Check_ボーダー境界(72.9998, 13.5, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー境界(73.4998, 13.5, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー境界(74.9995, 13.5, Rank.SSA, ComboStatus.None);
            Check_ボーダー境界(75.4995, 13.5, Rank.SSA, ComboStatus.FullCombo);
            Check_ボーダー境界(75.9995, 13.5, Rank.SSA, ComboStatus.AllJustice);
            Check_ボーダー境界(77.499, 13.5, Rank.SSS, ComboStatus.None);
            Check_ボーダー境界(77.999, 13.5, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー境界(78.499, 13.5, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー境界(81.2485, 13.5, Rank.Max, ComboStatus.None);
            Check_ボーダー境界(81.7485, 13.5, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー境界(82.2485, 13.5, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー境界(0, 13.6, Rank.C, ComboStatus.None);
            Check_ボーダー境界(0, 13.6, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー境界(0, 13.6, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー境界(21.49, 13.6, Rank.BBB, ComboStatus.None);
            Check_ボーダー境界(21.99, 13.6, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー境界(22.49, 13.6, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー境界(42.99, 13.6, Rank.A, ComboStatus.None);
            Check_ボーダー境界(43.49, 13.6, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー境界(43.99, 13.6, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー境界(52.99, 13.6, Rank.AA, ComboStatus.None);
            Check_ボーダー境界(53.49, 13.6, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー境界(53.99, 13.6, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー境界(67.99, 13.6, Rank.S, ComboStatus.None);
            Check_ボーダー境界(68.49, 13.6, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー境界(68.99, 13.6, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー境界(72.9998, 13.6, Rank.SS, ComboStatus.None);
            Check_ボーダー境界(73.4998, 13.6, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー境界(73.9998, 13.6, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー境界(75.4995, 13.6, Rank.SSA, ComboStatus.None);
            Check_ボーダー境界(75.9995, 13.6, Rank.SSA, ComboStatus.FullCombo);
            Check_ボーダー境界(76.4995, 13.6, Rank.SSA, ComboStatus.AllJustice);
            Check_ボーダー境界(77.999, 13.6, Rank.SSS, ComboStatus.None);
            Check_ボーダー境界(78.499, 13.6, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー境界(78.999, 13.6, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー境界(81.7485, 13.6, Rank.Max, ComboStatus.None);
            Check_ボーダー境界(82.2485, 13.6, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー境界(82.7485, 13.6, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー境界(0, 13.7, Rank.C, ComboStatus.None);
            Check_ボーダー境界(0, 13.7, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー境界(0, 13.7, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー境界(21.74, 13.7, Rank.BBB, ComboStatus.None);
            Check_ボーダー境界(22.24, 13.7, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー境界(22.74, 13.7, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー境界(43.49, 13.7, Rank.A, ComboStatus.None);
            Check_ボーダー境界(43.99, 13.7, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー境界(44.49, 13.7, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー境界(53.49, 13.7, Rank.AA, ComboStatus.None);
            Check_ボーダー境界(53.99, 13.7, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー境界(54.49, 13.7, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー境界(68.49, 13.7, Rank.S, ComboStatus.None);
            Check_ボーダー境界(68.99, 13.7, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー境界(69.49, 13.7, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー境界(73.4998, 13.7, Rank.SS, ComboStatus.None);
            Check_ボーダー境界(73.9998, 13.7, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー境界(74.4998, 13.7, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー境界(75.9995, 13.7, Rank.SSA, ComboStatus.None);
            Check_ボーダー境界(76.4995, 13.7, Rank.SSA, ComboStatus.FullCombo);
            Check_ボーダー境界(76.9995, 13.7, Rank.SSA, ComboStatus.AllJustice);
            Check_ボーダー境界(78.499, 13.7, Rank.SSS, ComboStatus.None);
            Check_ボーダー境界(78.999, 13.7, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー境界(79.499, 13.7, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー境界(82.2485, 13.7, Rank.Max, ComboStatus.None);
            Check_ボーダー境界(82.7485, 13.7, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー境界(83.2485, 13.7, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー境界(0, 13.8, Rank.C, ComboStatus.None);
            Check_ボーダー境界(0, 13.8, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー境界(0, 13.8, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー境界(21.99, 13.8, Rank.BBB, ComboStatus.None);
            Check_ボーダー境界(22.49, 13.8, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー境界(22.99, 13.8, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー境界(43.99, 13.8, Rank.A, ComboStatus.None);
            Check_ボーダー境界(44.49, 13.8, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー境界(44.99, 13.8, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー境界(53.99, 13.8, Rank.AA, ComboStatus.None);
            Check_ボーダー境界(54.49, 13.8, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー境界(54.99, 13.8, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー境界(68.99, 13.8, Rank.S, ComboStatus.None);
            Check_ボーダー境界(69.49, 13.8, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー境界(69.99, 13.8, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー境界(73.9998, 13.8, Rank.SS, ComboStatus.None);
            Check_ボーダー境界(74.4998, 13.8, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー境界(74.9998, 13.8, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー境界(76.4995, 13.8, Rank.SSA, ComboStatus.None);
            Check_ボーダー境界(76.9995, 13.8, Rank.SSA, ComboStatus.FullCombo);
            Check_ボーダー境界(77.4995, 13.8, Rank.SSA, ComboStatus.AllJustice);
            Check_ボーダー境界(78.999, 13.8, Rank.SSS, ComboStatus.None);
            Check_ボーダー境界(79.499, 13.8, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー境界(79.999, 13.8, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー境界(82.7485, 13.8, Rank.Max, ComboStatus.None);
            Check_ボーダー境界(83.2485, 13.8, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー境界(83.7485, 13.8, Rank.Max, ComboStatus.AllJustice);

            Check_ボーダー境界(0, 13.9, Rank.C, ComboStatus.None);
            Check_ボーダー境界(0, 13.9, Rank.C, ComboStatus.FullCombo);
            Check_ボーダー境界(0, 13.9, Rank.C, ComboStatus.AllJustice);
            Check_ボーダー境界(22.24, 13.9, Rank.BBB, ComboStatus.None);
            Check_ボーダー境界(22.74, 13.9, Rank.BBB, ComboStatus.FullCombo);
            Check_ボーダー境界(23.24, 13.9, Rank.BBB, ComboStatus.AllJustice);
            Check_ボーダー境界(44.49, 13.9, Rank.A, ComboStatus.None);
            Check_ボーダー境界(44.99, 13.9, Rank.A, ComboStatus.FullCombo);
            Check_ボーダー境界(45.49, 13.9, Rank.A, ComboStatus.AllJustice);
            Check_ボーダー境界(54.49, 13.9, Rank.AA, ComboStatus.None);
            Check_ボーダー境界(54.99, 13.9, Rank.AA, ComboStatus.FullCombo);
            Check_ボーダー境界(55.49, 13.9, Rank.AA, ComboStatus.AllJustice);
            Check_ボーダー境界(69.49, 13.9, Rank.S, ComboStatus.None);
            Check_ボーダー境界(69.99, 13.9, Rank.S, ComboStatus.FullCombo);
            Check_ボーダー境界(70.49, 13.9, Rank.S, ComboStatus.AllJustice);
            Check_ボーダー境界(74.4998, 13.9, Rank.SS, ComboStatus.None);
            Check_ボーダー境界(74.9998, 13.9, Rank.SS, ComboStatus.FullCombo);
            Check_ボーダー境界(75.4998, 13.9, Rank.SS, ComboStatus.AllJustice);
            Check_ボーダー境界(76.9995, 13.9, Rank.SSA, ComboStatus.None);
            Check_ボーダー境界(77.4995, 13.9, Rank.SSA, ComboStatus.FullCombo);
            Check_ボーダー境界(77.9995, 13.9, Rank.SSA, ComboStatus.AllJustice);
            Check_ボーダー境界(79.499, 13.9, Rank.SSS, ComboStatus.None);
            Check_ボーダー境界(79.999, 13.9, Rank.SSS, ComboStatus.FullCombo);
            Check_ボーダー境界(80.499, 13.9, Rank.SSS, ComboStatus.AllJustice);
            Check_ボーダー境界(83.2485, 13.9, Rank.Max, ComboStatus.None);
            Check_ボーダー境界(83.7485, 13.9, Rank.Max, ComboStatus.FullCombo);
            Check_ボーダー境界(84.2485, 13.9, Rank.Max, ComboStatus.AllJustice);
        }

        [TestMethod]
        public void GetOverPowerTest_中間値境界()
        {
            Check_中間値境界(0, 3.0, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値境界(0, 3.0, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値境界(0, 3.0, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値境界(7.49, 3.0, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値境界(7.99, 3.0, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値境界(8.49, 3.0, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値境界(17.4998, 3.0, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値境界(17.9998, 3.0, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値境界(18.4998, 3.0, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値境界(21.2495, 3.0, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値境界(21.7495, 3.0, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値境界(22.2495, 3.0, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値境界(23.749, 3.0, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値境界(24.249, 3.0, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値境界(24.749, 3.0, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値境界(26.8735, 3.0, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値境界(27.3735, 3.0, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値境界(27.8735, 3.0, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値境界(0, 5.0, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値境界(0, 5.0, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値境界(0, 5.0, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値境界(4.99, 5.0, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値境界(5.49, 5.0, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値境界(5.99, 5.0, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値境界(17.49, 5.0, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値境界(17.99, 5.0, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値境界(18.49, 5.0, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値境界(27.4998, 5.0, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値境界(27.9998, 5.0, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値境界(28.4998, 5.0, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値境界(31.2495, 5.0, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値境界(31.7495, 5.0, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値境界(32.2495, 5.0, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値境界(33.749, 5.0, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値境界(34.249, 5.0, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値境界(34.749, 5.0, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);

            Check_中間値境界(0, 13.0, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値境界(0, 13.0, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値境界(0, 13.0, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値境界(9.99, 13.0, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値境界(10.49, 13.0, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値境界(10.99, 13.0, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値境界(29.99, 13.0, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値境界(30.49, 13.0, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値境界(30.99, 13.0, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値境界(44.99, 13.0, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値境界(45.49, 13.0, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値境界(45.99, 13.0, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値境界(57.49, 13.0, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値境界(57.99, 13.0, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値境界(58.49, 13.0, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値境界(67.4998, 13.0, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値境界(67.9998, 13.0, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値境界(68.4998, 13.0, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値境界(71.2495, 13.0, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値境界(71.7495, 13.0, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値境界(72.2495, 13.0, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値境界(73.749, 13.0, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値境界(74.249, 13.0, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値境界(74.749, 13.0, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値境界(76.8735, 13.0, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値境界(77.3735, 13.0, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値境界(77.8735, 13.0, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値境界(0, 13.1, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値境界(0, 13.1, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値境界(0, 13.1, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値境界(10.12, 13.1, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値境界(10.62, 13.1, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値境界(11.12, 13.1, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値境界(30.37, 13.1, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値境界(30.87, 13.1, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値境界(31.37, 13.1, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値境界(45.49, 13.1, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値境界(45.99, 13.1, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値境界(46.49, 13.1, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値境界(57.99, 13.1, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値境界(58.49, 13.1, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値境界(58.99, 13.1, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値境界(67.9998, 13.1, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値境界(68.4998, 13.1, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値境界(68.9998, 13.1, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値境界(71.7495, 13.1, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値境界(72.2495, 13.1, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値境界(72.7495, 13.1, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値境界(74.249, 13.1, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値境界(74.749, 13.1, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値境界(75.249, 13.1, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値境界(77.3735, 13.1, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値境界(77.8735, 13.1, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値境界(78.3735, 13.1, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値境界(0, 13.2, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値境界(0, 13.2, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値境界(0, 13.2, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値境界(10.24, 13.2, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値境界(10.74, 13.2, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値境界(11.24, 13.2, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値境界(30.74, 13.2, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値境界(31.24, 13.2, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値境界(31.74, 13.2, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値境界(45.99, 13.2, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値境界(46.49, 13.2, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値境界(46.99, 13.2, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値境界(58.49, 13.2, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値境界(58.99, 13.2, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値境界(59.49, 13.2, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値境界(68.4998, 13.2, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値境界(68.9998, 13.2, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値境界(69.4998, 13.2, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値境界(72.2495, 13.2, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値境界(72.7495, 13.2, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値境界(73.2495, 13.2, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値境界(74.749, 13.2, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値境界(75.249, 13.2, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値境界(75.749, 13.2, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値境界(77.8735, 13.2, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値境界(78.3735, 13.2, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値境界(78.8735, 13.2, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値境界(0, 13.3, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値境界(0, 13.3, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値境界(0, 13.3, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値境界(10.37, 13.3, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値境界(10.87, 13.3, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値境界(11.37, 13.3, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値境界(31.12, 13.3, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値境界(31.62, 13.3, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値境界(32.12, 13.3, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値境界(46.49, 13.3, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値境界(46.99, 13.3, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値境界(47.49, 13.3, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値境界(58.99, 13.3, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値境界(59.49, 13.3, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値境界(59.99, 13.3, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値境界(68.9998, 13.3, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値境界(69.4998, 13.3, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値境界(69.9998, 13.3, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値境界(72.7495, 13.3, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値境界(73.2495, 13.3, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値境界(73.7495, 13.3, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値境界(75.249, 13.3, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値境界(75.749, 13.3, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値境界(76.249, 13.3, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値境界(78.3735, 13.3, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値境界(78.8735, 13.3, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値境界(79.3735, 13.3, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値境界(0, 13.4, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値境界(0, 13.4, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値境界(0, 13.4, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値境界(10.49, 13.4, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値境界(10.99, 13.4, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値境界(11.49, 13.4, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値境界(31.49, 13.4, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値境界(31.99, 13.4, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値境界(32.49, 13.4, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値境界(46.99, 13.4, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値境界(47.49, 13.4, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値境界(47.99, 13.4, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値境界(59.49, 13.4, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値境界(59.99, 13.4, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値境界(60.49, 13.4, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値境界(69.4998, 13.4, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値境界(69.9998, 13.4, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値境界(70.4998, 13.4, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値境界(73.2495, 13.4, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値境界(73.7495, 13.4, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値境界(74.2495, 13.4, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値境界(75.749, 13.4, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値境界(76.249, 13.4, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値境界(76.749, 13.4, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値境界(78.8735, 13.4, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値境界(79.3735, 13.4, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値境界(79.8735, 13.4, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値境界(0, 13.5, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値境界(0, 13.5, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値境界(0, 13.5, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値境界(10.62, 13.5, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値境界(11.12, 13.5, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値境界(11.62, 13.5, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値境界(31.87, 13.5, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値境界(32.37, 13.5, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値境界(32.87, 13.5, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値境界(47.49, 13.5, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値境界(47.99, 13.5, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値境界(48.49, 13.5, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値境界(59.99, 13.5, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値境界(60.49, 13.5, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値境界(60.99, 13.5, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値境界(69.9998, 13.5, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値境界(70.4998, 13.5, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値境界(70.9998, 13.5, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値境界(73.7495, 13.5, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値境界(74.2495, 13.5, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値境界(74.7495, 13.5, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値境界(76.249, 13.5, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値境界(76.749, 13.5, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値境界(77.249, 13.5, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値境界(79.3735, 13.5, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値境界(79.8735, 13.5, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値境界(80.3735, 13.5, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値境界(0, 13.6, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値境界(0, 13.6, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値境界(0, 13.6, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値境界(10.74, 13.6, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値境界(11.24, 13.6, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値境界(11.74, 13.6, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値境界(32.24, 13.6, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値境界(32.74, 13.6, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値境界(33.24, 13.6, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値境界(47.99, 13.6, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値境界(48.49, 13.6, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値境界(48.99, 13.6, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値境界(60.49, 13.6, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値境界(60.99, 13.6, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値境界(61.49, 13.6, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値境界(70.4998, 13.6, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値境界(70.9998, 13.6, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値境界(71.4998, 13.6, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値境界(74.2495, 13.6, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値境界(74.7495, 13.6, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値境界(75.2495, 13.6, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値境界(76.749, 13.6, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値境界(77.249, 13.6, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値境界(77.749, 13.6, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値境界(79.8735, 13.6, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値境界(80.3735, 13.6, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値境界(80.8735, 13.6, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値境界(0, 13.7, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値境界(0, 13.7, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値境界(0, 13.7, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値境界(10.87, 13.7, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値境界(11.37, 13.7, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値境界(11.87, 13.7, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値境界(32.62, 13.7, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値境界(33.12, 13.7, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値境界(33.62, 13.7, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値境界(48.49, 13.7, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値境界(48.99, 13.7, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値境界(49.49, 13.7, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値境界(60.99, 13.7, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値境界(61.49, 13.7, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値境界(61.99, 13.7, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値境界(70.9998, 13.7, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値境界(71.4998, 13.7, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値境界(71.9998, 13.7, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値境界(74.7495, 13.7, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値境界(75.2495, 13.7, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値境界(75.7495, 13.7, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値境界(77.249, 13.7, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値境界(77.749, 13.7, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値境界(78.249, 13.7, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値境界(80.3735, 13.7, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値境界(80.8735, 13.7, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値境界(81.3735, 13.7, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値境界(0, 13.8, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値境界(0, 13.8, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値境界(0, 13.8, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値境界(10.99, 13.8, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値境界(11.49, 13.8, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値境界(11.99, 13.8, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値境界(32.99, 13.8, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値境界(33.49, 13.8, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値境界(33.99, 13.8, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値境界(48.99, 13.8, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値境界(49.49, 13.8, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値境界(49.99, 13.8, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値境界(61.49, 13.8, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値境界(61.99, 13.8, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値境界(62.49, 13.8, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値境界(71.4998, 13.8, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値境界(71.9998, 13.8, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値境界(72.4998, 13.8, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値境界(75.2495, 13.8, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値境界(75.7495, 13.8, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値境界(76.2495, 13.8, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値境界(77.749, 13.8, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値境界(78.249, 13.8, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値境界(78.749, 13.8, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値境界(80.8735, 13.8, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値境界(81.3735, 13.8, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値境界(81.8735, 13.8, Rank.SSS, Rank.Max, ComboStatus.AllJustice);

            Check_中間値境界(0, 13.9, Rank.D, Rank.C, ComboStatus.None);
            Check_中間値境界(0, 13.9, Rank.D, Rank.C, ComboStatus.FullCombo);
            Check_中間値境界(0, 13.9, Rank.D, Rank.C, ComboStatus.AllJustice);
            Check_中間値境界(11.12, 13.9, Rank.C, Rank.BBB, ComboStatus.None);
            Check_中間値境界(11.62, 13.9, Rank.C, Rank.BBB, ComboStatus.FullCombo);
            Check_中間値境界(12.12, 13.9, Rank.C, Rank.BBB, ComboStatus.AllJustice);
            Check_中間値境界(33.37, 13.9, Rank.BBB, Rank.A, ComboStatus.None);
            Check_中間値境界(33.87, 13.9, Rank.BBB, Rank.A, ComboStatus.FullCombo);
            Check_中間値境界(34.37, 13.9, Rank.BBB, Rank.A, ComboStatus.AllJustice);
            Check_中間値境界(49.49, 13.9, Rank.A, Rank.AA, ComboStatus.None);
            Check_中間値境界(49.99, 13.9, Rank.A, Rank.AA, ComboStatus.FullCombo);
            Check_中間値境界(50.49, 13.9, Rank.A, Rank.AA, ComboStatus.AllJustice);
            Check_中間値境界(61.99, 13.9, Rank.AA, Rank.S, ComboStatus.None);
            Check_中間値境界(62.49, 13.9, Rank.AA, Rank.S, ComboStatus.FullCombo);
            Check_中間値境界(62.99, 13.9, Rank.AA, Rank.S, ComboStatus.AllJustice);
            Check_中間値境界(71.9998, 13.9, Rank.S, Rank.SS, ComboStatus.None);
            Check_中間値境界(72.4998, 13.9, Rank.S, Rank.SS, ComboStatus.FullCombo);
            Check_中間値境界(72.9998, 13.9, Rank.S, Rank.SS, ComboStatus.AllJustice);
            Check_中間値境界(75.7495, 13.9, Rank.SS, Rank.SSA, ComboStatus.None);
            Check_中間値境界(76.2495, 13.9, Rank.SS, Rank.SSA, ComboStatus.FullCombo);
            Check_中間値境界(76.7495, 13.9, Rank.SS, Rank.SSA, ComboStatus.AllJustice);
            Check_中間値境界(78.249, 13.9, Rank.SSA, Rank.SSS, ComboStatus.None);
            Check_中間値境界(78.749, 13.9, Rank.SSA, Rank.SSS, ComboStatus.FullCombo);
            Check_中間値境界(79.249, 13.9, Rank.SSA, Rank.SSS, ComboStatus.AllJustice);
            Check_中間値境界(81.3735, 13.9, Rank.SSS, Rank.Max, ComboStatus.None);
            Check_中間値境界(81.8735, 13.9, Rank.SSS, Rank.Max, ComboStatus.FullCombo);
            Check_中間値境界(82.3735, 13.9, Rank.SSS, Rank.Max, ComboStatus.AllJustice);
        }

        [TestMethod]
        public void GetOverPowerTest_範囲外()
        {
            Check_範囲外(0, 0, 0, ComboStatus.None);
            Check_範囲外(0, 0, 0, ComboStatus.FullCombo);
            Check_範囲外(0, 0, 0, ComboStatus.AllJustice);
            Check_範囲外(0, 0, Utility.GetBorderScore(Rank.S), ComboStatus.None);
            Check_範囲外(0, 0, Utility.GetBorderScore(Rank.S), ComboStatus.FullCombo);
            Check_範囲外(0, 0, Utility.GetBorderScore(Rank.S), ComboStatus.AllJustice);
            Check_範囲外(0, 0, Utility.GetBorderScore(Rank.Max), ComboStatus.None);
            Check_範囲外(0, 0, Utility.GetBorderScore(Rank.Max), ComboStatus.FullCombo);
            Check_範囲外(0, 0, Utility.GetBorderScore(Rank.Max), ComboStatus.AllJustice);
            Check_範囲外(0, 0, 10000000, ComboStatus.None);
            Check_範囲外(0, 0, 10000000, ComboStatus.FullCombo);
            Check_範囲外(0, 0, 10000000, ComboStatus.AllJustice);

            Check_範囲外(0, -1, 0, ComboStatus.None);
            Check_範囲外(0, -1, 0, ComboStatus.FullCombo);
            Check_範囲外(0, -1, 0, ComboStatus.AllJustice);
            Check_範囲外(0, -1, Utility.GetBorderScore(Rank.S), ComboStatus.None);
            Check_範囲外(0, -1, Utility.GetBorderScore(Rank.S), ComboStatus.FullCombo);
            Check_範囲外(0, -1, Utility.GetBorderScore(Rank.S), ComboStatus.AllJustice);
            Check_範囲外(0, -1, Utility.GetBorderScore(Rank.Max), ComboStatus.None);
            Check_範囲外(0, -1, Utility.GetBorderScore(Rank.Max), ComboStatus.FullCombo);
            Check_範囲外(0, -1, Utility.GetBorderScore(Rank.Max), ComboStatus.AllJustice);
            Check_範囲外(0, -1, 10000000, ComboStatus.None);
            Check_範囲外(0, -1, 10000000, ComboStatus.FullCombo);
            Check_範囲外(0, -1, 10000000, ComboStatus.AllJustice);

            Check_範囲外(0, 3, -1, ComboStatus.None);
            Check_範囲外(0, 3, -1, ComboStatus.FullCombo);
            Check_範囲外(0, 3, -1, ComboStatus.AllJustice);
            Check_範囲外(30, 3, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.None);
            Check_範囲外(30, 3, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.FullCombo);
            Check_範囲外(30, 3, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.AllJustice);

            Check_範囲外(0, 5, -1, ComboStatus.None);
            Check_範囲外(0, 5, -1, ComboStatus.FullCombo);
            Check_範囲外(0, 5, -1, ComboStatus.AllJustice);
            Check_範囲外(40, 5, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.None);
            Check_範囲外(40, 5, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.FullCombo);
            Check_範囲外(40, 5, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.AllJustice);

            Check_範囲外(0, 6, -1, ComboStatus.None);
            Check_範囲外(0, 6, -1, ComboStatus.FullCombo);
            Check_範囲外(0, 6, -1, ComboStatus.AllJustice);
            Check_範囲外(45, 6, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.None);
            Check_範囲外(45, 6, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.FullCombo);
            Check_範囲外(45, 6, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.AllJustice);

            Check_範囲外(0, 13.0, -1, ComboStatus.None);
            Check_範囲外(0, 13.0, -1, ComboStatus.FullCombo);
            Check_範囲外(0, 13.0, -1, ComboStatus.AllJustice);
            Check_範囲外(80.0, 13.0, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.None);
            Check_範囲外(80.0, 13.0, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.FullCombo);
            Check_範囲外(80.0, 13.0, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.AllJustice);

            Check_範囲外(0, 13.1, -1, ComboStatus.None);
            Check_範囲外(0, 13.1, -1, ComboStatus.FullCombo);
            Check_範囲外(0, 13.1, -1, ComboStatus.AllJustice);
            Check_範囲外(80.5, 13.1, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.None);
            Check_範囲外(80.5, 13.1, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.FullCombo);
            Check_範囲外(80.5, 13.1, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.AllJustice);

            Check_範囲外(0, 13.2, -1, ComboStatus.None);
            Check_範囲外(0, 13.2, -1, ComboStatus.FullCombo);
            Check_範囲外(0, 13.2, -1, ComboStatus.AllJustice);
            Check_範囲外(81.0, 13.2, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.None);
            Check_範囲外(81.0, 13.2, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.FullCombo);
            Check_範囲外(81.0, 13.2, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.AllJustice);

            Check_範囲外(0, 13.3, -1, ComboStatus.None);
            Check_範囲外(0, 13.3, -1, ComboStatus.FullCombo);
            Check_範囲外(0, 13.3, -1, ComboStatus.AllJustice);
            Check_範囲外(81.5, 13.3, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.None);
            Check_範囲外(81.5, 13.3, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.FullCombo);
            Check_範囲外(81.5, 13.3, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.AllJustice);

            Check_範囲外(0, 13.4, -1, ComboStatus.None);
            Check_範囲外(0, 13.4, -1, ComboStatus.FullCombo);
            Check_範囲外(0, 13.4, -1, ComboStatus.AllJustice);
            Check_範囲外(82.0, 13.4, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.None);
            Check_範囲外(82.0, 13.4, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.FullCombo);
            Check_範囲外(82.0, 13.4, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.AllJustice);

            Check_範囲外(0, 13.5, -1, ComboStatus.None);
            Check_範囲外(0, 13.5, -1, ComboStatus.FullCombo);
            Check_範囲外(0, 13.5, -1, ComboStatus.AllJustice);
            Check_範囲外(82.5, 13.5, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.None);
            Check_範囲外(82.5, 13.5, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.FullCombo);
            Check_範囲外(82.5, 13.5, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.AllJustice);

            Check_範囲外(0, 13.6, -1, ComboStatus.None);
            Check_範囲外(0, 13.6, -1, ComboStatus.FullCombo);
            Check_範囲外(0, 13.6, -1, ComboStatus.AllJustice);
            Check_範囲外(83.0, 13.6, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.None);
            Check_範囲外(83.0, 13.6, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.FullCombo);
            Check_範囲外(83.0, 13.6, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.AllJustice);

            Check_範囲外(0, 13.7, -1, ComboStatus.None);
            Check_範囲外(0, 13.7, -1, ComboStatus.FullCombo);
            Check_範囲外(0, 13.7, -1, ComboStatus.AllJustice);
            Check_範囲外(83.5, 13.7, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.None);
            Check_範囲外(83.5, 13.7, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.FullCombo);
            Check_範囲外(83.5, 13.7, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.AllJustice);

            Check_範囲外(0, 13.8, -1, ComboStatus.None);
            Check_範囲外(0, 13.8, -1, ComboStatus.FullCombo);
            Check_範囲外(0, 13.8, -1, ComboStatus.AllJustice);
            Check_範囲外(84.0, 13.8, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.None);
            Check_範囲外(84.0, 13.8, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.FullCombo);
            Check_範囲外(84.0, 13.8, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.AllJustice);

            Check_範囲外(0, 13.9, -1, ComboStatus.None);
            Check_範囲外(0, 13.9, -1, ComboStatus.FullCombo);
            Check_範囲外(0, 13.9, -1, ComboStatus.AllJustice);
            Check_範囲外(84.5, 13.9, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.None);
            Check_範囲外(84.5, 13.9, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.FullCombo);
            Check_範囲外(84.5, 13.9, Utility.GetBorderScore(Rank.Max) + 1, ComboStatus.AllJustice);
        }
    }
}
